language: python

matrix:
  include:
  - python: '3.5'
  - python: '3.6'
  - python: '3.7'
  - python: '3.8'
  - python: '3.9'

services:
  - xvfb

addons:
  apt:
    packages:
      # Needed to start x virtual framebuffer (this is not the right way...)
      - libxcb1
      - libxkbcommon-x11-0
      - libxcb-icccm4
      - libxcb-image0
      - libxcb-keysyms1
      - libxcb-randr0
      - libxcb-render-util0
      - libxcb-xinerama0

install:
- pip install --upgrade pip
- pip install -r requirements.txt
- pip install ".[CPP, test]"

script:
- python -m unittest -v -b

deploy:
  # pypy test deployment
  - provider: pypi
    distributions: sdist
    server: https://test.pypi.org/legacy/
    user: cklb
    password:
      secure: "XpY7JwX5ZDIxbCHz8VzRAQT+1xdrE4Li5f3guRsriJrhpvXWTl6/fisttsHM380csWGnHYy1NoRt70rwIrInaiJBfbICXrniSsHr9DO5EnqGw+cso11cbJej+kMwRt9Ff3DaNsYRUuOMGsnna4tKSloev7CEFXxRDDaeuT8sPbDtWWGFIrpyvroyKo15dFe1nT+R2WTJtKjfU0P9k/FGESk7VK3s/XhEr1uSEx/fQmq/0i+8ltxwFfxEA8QJuYUUiJOj577pQYl11qUOANW5KxSmy2w3pOy/UEobz2RNpi/A+gsZnO8xvQXntHEKZ7+uU0QWuNkJL8j1VUjXlGgvs/I4gq8+UtmZTNja1X3666m+JqOx1ZxaiZ6a3zhxRhGqGHuA/Ks6rTJcBa7N7CbAAbOkUsRqnygCCm+4Ej+j31vVfI3g7dojhhVhGdrXr+LIbkXEAyIPqbkoFCUuE+nErDhbaXxYOS9sHHqldpTcutEtWcg3NTac9p7/QLUZGGlKPj2ubp0gKs1Smt3T6CzDnfk+omlCCRl7wdvDeo6gx5304sqJDYau2j6iDDlzVLvDTUR5JanY/xyPTs90fpDjJqhISvSE4657GRDbOc4lSqop4RZHuW8bVeUSeNxMLDv/6UoKULXd8UBSFLHYoQDF6UBYsEivkAF/A1lJ40HcBZo="
    on:
      branch: master
      tags: false
      condition: $TRAVIS_PYTHON_VERSION = "3.8"

  # pypy deployment
  - provider: pypi
    distributions: sdist
    user: cklb
    password:
      secure: "WKFKDgsXpoNPPedpgG6W7avL7CHbsFYtTbd41QlnJiBd2qBsI0x2qYsGVrQgC8adCwh8prXCLp+Xs+xR259tyGo6uzrJg/6WyNx5D9IWORizUI7Wa3odYwoK0jN/vK4Rq9TttKbCYI7hjQFs0Dbj+wIZMuPdutqVBSTfPEbOZYKBN2wrqO0gtH5Wc4wjEvWSrGacxmJ1gQaZqwu0LsgbQPjH7wFFV6qX//gOQUEaRNWU6UjoJnLVFV3bhc2GmdGRx7y2qUkP7SQmJoGCB2rtWOT+DeMjbZqq1IplUoWZPJs8cSei8nm+L1wA4DhFUVbm1IhhSHREpMA+KwLbygp79ml2QCOvrHmU+T5SmyHkvI8FJAMX28KuinUU2RC4VIJuvKhTS+IS7yBKOoV1lismMgGbtWafhEHUz6YKOoIDjSPaNOA1/9E2xsIxBXeFmoEDx6tO4wCGT3/da79e8b5Iv6gDR0LdqMD4Dmfzdy7CAbHFw21QwwncSc6t6scYUPUHMfFGc2lrX8wos7EeNHU62a55pZRr38RXSYzE5D0RcGT8VRcufd/2S7redXbPD79O5mDbZJw8aBqx5DVRH4emakVacg3N+CiiyAYstMfGF0tZSrqQFHNsSukZjo1SktxpgcdmjfKx6yA/sWr3LBKcT1p5uOyVEfKrx30ygtyhrPw="
    on:
      branch: master
      tags: true
    condition: $TRAVIS_PYTHON_VERSION = "3.8"
